### ISSUE TITLE
CARTO DW extension not found for users outside gcp-us-east1 region using OAuth

### ISSUE THREAD

**Issue by Mmoncadaisla** [CartoDB/carto-auth#4]
### Context

When authenticating to a CARTO account via OAuth and fetching the CARTO DW client through the `get_carto_dw_client` method with an account in a different region from the [default one](https://github.com/CartoDB/carto-auth/blob/6f937892ef074ddaedc15121914c20ee9336d910/carto_auth/auth.py#L11), it fails since the CARTO DW connection cannot be found (as it's looking into the wrong tenant), but failing with a misleading error [here](https://github.com/CartoDB/carto-auth/blob/master/carto_auth/auth.py#L169-L171).

```python
import requests
from carto_auth import CartoAuth

carto_auth = CartoAuth.from_oauth()

url = f"{carto_auth.api_base_url}/v3/connections/carto-dw/token"
headers = carto_auth._api_headers()
response = requests.get(url, headers=headers)
creds = response.json()

creds
```

```json
{"error": "Connection not found",
 "status": 404,
 "message": "Connection not found",
 "connection_name": "carto_dw",
 "connectionName": "carto_dw"}
```

### Steps to replicate

1. Create a `conda` environment from this file [env_export.yml.zip](https://github.com/CartoDB/carto-auth/files/9859190/env_export.yml.zip)

```bash
conda create -f env_export.yml
```

2. Run the following code and authenticate against a CARTO account in (for example) EU tenant

```python
from carto_auth import CartoAuth
carto_auth = CartoAuth.from_oauth()
carto_dw_client = carto_auth.get_carto_dw_client()
```

```
Error: CARTO DW extension not found.
Please, install carto-auth[carto-dw]
```
### Additional comments

From the user perspective, the API base URL would ideally be automatically retrieved when using the `from_oauth` method. Alternatively, we would throw a better error to the user, maybe something similar to:

![image](https://user-images.githubusercontent.com/48254102/197750941-a627a0bf-6e41-4610-8707-e31c12f57851.png)

cc @Jesus89

**Comment by Jesus89** [comment]
Hi @Mmoncadaisla,

Have you tried passing the api_base_url to the function?

For example:

```py
from carto_auth import CartoAuth
carto_auth = CartoAuth.from_oauth(api_base_url="https://gcp-europe-west1.api.carto.com")
project, token = carto_auth.get_carto_dw_credentials()
```

**Comment by Mmoncadaisla** [comment]
Hi @Jesus89 thanks for the prompt reply. 

Yes, that works. However, the issue is not the lack of ability to work with the CARTO DW but the lack/misleading information provided to the user when this is not provided and the user's region is different from `gcp-us-east1`. 

In our humble opinion, ideally, users wouldn't need to take care of setting the `api_base_url` when using OAuth. Nonetheless, if this is a hard constraint, we could maybe at least consider displaying a more relevant message, for example:

#### Current message

>Error: CARTO DW extension not found.
>Please, install carto-auth[carto-dw]

#### Example proposed messaging

>Error: CARTO DW connection not found.
>Please, make sure that api_base_url is correctly defined.


```diff
--- a/carto_auth/auth.py
+++ b/carto_auth/auth.py
@@ -151,8 +151,14 @@ class CartoAuth:
         headers = self._api_headers()

         response = requests.get(url, headers=headers)
+        if response.status_code != 200:
+            error_msg = response.json()
+            msg = error_msg.get("error")
+            if response.status_code == 404:
+                sys.stderr.write("Error: CARTO DW connection not found.\n")
+                sys.stderr.write("Please, make sure api_base_url parameter is correctly defined.\n")
+            raise CredentialsError(msg)
         creds = response.json()
-
         return creds["projectId"], creds["token"]

     def get_carto_dw_client(self):
@@ -163,13 +169,13 @@ class CartoAuth:
         try:
             from google.cloud.bigquery import Client
             from google.oauth2.credentials import Credentials
-
-            cdw_project, cdw_token = self.get_carto_dw_credentials()
-            return Client(cdw_project, credentials=Credentials(cdw_token))
         except Exception:
             sys.stderr.write("Error: CARTO DW extension not found.\n")
             sys.stderr.write("Please, install carto-auth[carto-dw]\n")

+        cdw_project, cdw_token = self.get_carto_dw_credentials()
+        return Client(cdw_project, credentials=Credentials(cdw_token))
+
     def get_access_token(self):
         if self._access_token and not self._token_expired():
             return self._access_token
```

Please let us know if that'd make sense 🙇🏼‍♂️

**Comment by Jesus89** [comment]
Hi @Mmoncadaisla.

I'm checking with the infrastructure team about a way to obtain the API Base URL programmatically.

Regarding the error messages, totally agree. Status code 200 can have invalid JSON too, but I get your suggestion.
